[build]
  base = "portfolio"
  publish = "portfolio/public"
  command = "hugo"  # Simplified command, no need to install Hugo globally

[context.production.environment]
  HUGO_VERSION = "0.117.0"  # Specify the desired Hugo version
  HUGO_EXTENDED = "true"     # Optional, remove if not necessary
